/**
 * Eurofurence API for Mobile Apps
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.DeltaResponseAnnouncementRecord;
import io.swagger.client.model.DeltaResponseDealerRecord;
import io.swagger.client.model.DeltaResponseEventConferenceDayRecord;
import io.swagger.client.model.DeltaResponseEventConferenceRoomRecord;
import io.swagger.client.model.DeltaResponseEventConferenceTrackRecord;
import io.swagger.client.model.DeltaResponseEventRecord;
import io.swagger.client.model.DeltaResponseImageRecord;
import io.swagger.client.model.DeltaResponseKnowledgeEntryRecord;
import io.swagger.client.model.DeltaResponseKnowledgeGroupRecord;
import io.swagger.client.model.DeltaResponseMapRecord;
import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class AggregatedDeltaResponse {
  
  @SerializedName("Since")
  private Date since = null;
  @SerializedName("CurrentDateTimeUtc")
  private Date currentDateTimeUtc = null;
  @SerializedName("Events")
  private DeltaResponseEventRecord events = null;
  @SerializedName("EventConferenceDays")
  private DeltaResponseEventConferenceDayRecord eventConferenceDays = null;
  @SerializedName("EventConferenceRooms")
  private DeltaResponseEventConferenceRoomRecord eventConferenceRooms = null;
  @SerializedName("EventConferenceTracks")
  private DeltaResponseEventConferenceTrackRecord eventConferenceTracks = null;
  @SerializedName("KnowledgeGroups")
  private DeltaResponseKnowledgeGroupRecord knowledgeGroups = null;
  @SerializedName("KnowledgeEntries")
  private DeltaResponseKnowledgeEntryRecord knowledgeEntries = null;
  @SerializedName("Images")
  private DeltaResponseImageRecord images = null;
  @SerializedName("Dealers")
  private DeltaResponseDealerRecord dealers = null;
  @SerializedName("Announcements")
  private DeltaResponseAnnouncementRecord announcements = null;
  @SerializedName("Maps")
  private DeltaResponseMapRecord maps = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getSince() {
    return since;
  }
  public void setSince(Date since) {
    this.since = since;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getCurrentDateTimeUtc() {
    return currentDateTimeUtc;
  }
  public void setCurrentDateTimeUtc(Date currentDateTimeUtc) {
    this.currentDateTimeUtc = currentDateTimeUtc;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public DeltaResponseEventRecord getEvents() {
    return events;
  }
  public void setEvents(DeltaResponseEventRecord events) {
    this.events = events;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public DeltaResponseEventConferenceDayRecord getEventConferenceDays() {
    return eventConferenceDays;
  }
  public void setEventConferenceDays(DeltaResponseEventConferenceDayRecord eventConferenceDays) {
    this.eventConferenceDays = eventConferenceDays;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public DeltaResponseEventConferenceRoomRecord getEventConferenceRooms() {
    return eventConferenceRooms;
  }
  public void setEventConferenceRooms(DeltaResponseEventConferenceRoomRecord eventConferenceRooms) {
    this.eventConferenceRooms = eventConferenceRooms;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public DeltaResponseEventConferenceTrackRecord getEventConferenceTracks() {
    return eventConferenceTracks;
  }
  public void setEventConferenceTracks(DeltaResponseEventConferenceTrackRecord eventConferenceTracks) {
    this.eventConferenceTracks = eventConferenceTracks;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public DeltaResponseKnowledgeGroupRecord getKnowledgeGroups() {
    return knowledgeGroups;
  }
  public void setKnowledgeGroups(DeltaResponseKnowledgeGroupRecord knowledgeGroups) {
    this.knowledgeGroups = knowledgeGroups;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public DeltaResponseKnowledgeEntryRecord getKnowledgeEntries() {
    return knowledgeEntries;
  }
  public void setKnowledgeEntries(DeltaResponseKnowledgeEntryRecord knowledgeEntries) {
    this.knowledgeEntries = knowledgeEntries;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public DeltaResponseImageRecord getImages() {
    return images;
  }
  public void setImages(DeltaResponseImageRecord images) {
    this.images = images;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public DeltaResponseDealerRecord getDealers() {
    return dealers;
  }
  public void setDealers(DeltaResponseDealerRecord dealers) {
    this.dealers = dealers;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public DeltaResponseAnnouncementRecord getAnnouncements() {
    return announcements;
  }
  public void setAnnouncements(DeltaResponseAnnouncementRecord announcements) {
    this.announcements = announcements;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public DeltaResponseMapRecord getMaps() {
    return maps;
  }
  public void setMaps(DeltaResponseMapRecord maps) {
    this.maps = maps;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AggregatedDeltaResponse aggregatedDeltaResponse = (AggregatedDeltaResponse) o;
    return (this.since == null ? aggregatedDeltaResponse.since == null : this.since.equals(aggregatedDeltaResponse.since)) &&
        (this.currentDateTimeUtc == null ? aggregatedDeltaResponse.currentDateTimeUtc == null : this.currentDateTimeUtc.equals(aggregatedDeltaResponse.currentDateTimeUtc)) &&
        (this.events == null ? aggregatedDeltaResponse.events == null : this.events.equals(aggregatedDeltaResponse.events)) &&
        (this.eventConferenceDays == null ? aggregatedDeltaResponse.eventConferenceDays == null : this.eventConferenceDays.equals(aggregatedDeltaResponse.eventConferenceDays)) &&
        (this.eventConferenceRooms == null ? aggregatedDeltaResponse.eventConferenceRooms == null : this.eventConferenceRooms.equals(aggregatedDeltaResponse.eventConferenceRooms)) &&
        (this.eventConferenceTracks == null ? aggregatedDeltaResponse.eventConferenceTracks == null : this.eventConferenceTracks.equals(aggregatedDeltaResponse.eventConferenceTracks)) &&
        (this.knowledgeGroups == null ? aggregatedDeltaResponse.knowledgeGroups == null : this.knowledgeGroups.equals(aggregatedDeltaResponse.knowledgeGroups)) &&
        (this.knowledgeEntries == null ? aggregatedDeltaResponse.knowledgeEntries == null : this.knowledgeEntries.equals(aggregatedDeltaResponse.knowledgeEntries)) &&
        (this.images == null ? aggregatedDeltaResponse.images == null : this.images.equals(aggregatedDeltaResponse.images)) &&
        (this.dealers == null ? aggregatedDeltaResponse.dealers == null : this.dealers.equals(aggregatedDeltaResponse.dealers)) &&
        (this.announcements == null ? aggregatedDeltaResponse.announcements == null : this.announcements.equals(aggregatedDeltaResponse.announcements)) &&
        (this.maps == null ? aggregatedDeltaResponse.maps == null : this.maps.equals(aggregatedDeltaResponse.maps));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.since == null ? 0: this.since.hashCode());
    result = 31 * result + (this.currentDateTimeUtc == null ? 0: this.currentDateTimeUtc.hashCode());
    result = 31 * result + (this.events == null ? 0: this.events.hashCode());
    result = 31 * result + (this.eventConferenceDays == null ? 0: this.eventConferenceDays.hashCode());
    result = 31 * result + (this.eventConferenceRooms == null ? 0: this.eventConferenceRooms.hashCode());
    result = 31 * result + (this.eventConferenceTracks == null ? 0: this.eventConferenceTracks.hashCode());
    result = 31 * result + (this.knowledgeGroups == null ? 0: this.knowledgeGroups.hashCode());
    result = 31 * result + (this.knowledgeEntries == null ? 0: this.knowledgeEntries.hashCode());
    result = 31 * result + (this.images == null ? 0: this.images.hashCode());
    result = 31 * result + (this.dealers == null ? 0: this.dealers.hashCode());
    result = 31 * result + (this.announcements == null ? 0: this.announcements.hashCode());
    result = 31 * result + (this.maps == null ? 0: this.maps.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AggregatedDeltaResponse {\n");
    
    sb.append("  since: ").append(since).append("\n");
    sb.append("  currentDateTimeUtc: ").append(currentDateTimeUtc).append("\n");
    sb.append("  events: ").append(events).append("\n");
    sb.append("  eventConferenceDays: ").append(eventConferenceDays).append("\n");
    sb.append("  eventConferenceRooms: ").append(eventConferenceRooms).append("\n");
    sb.append("  eventConferenceTracks: ").append(eventConferenceTracks).append("\n");
    sb.append("  knowledgeGroups: ").append(knowledgeGroups).append("\n");
    sb.append("  knowledgeEntries: ").append(knowledgeEntries).append("\n");
    sb.append("  images: ").append(images).append("\n");
    sb.append("  dealers: ").append(dealers).append("\n");
    sb.append("  announcements: ").append(announcements).append("\n");
    sb.append("  maps: ").append(maps).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
