/**
 * Eurofurence API for Mobile Apps
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Date;
import java.util.UUID;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class AnnouncementRecord {
  
  @SerializedName("LastChangeDateTimeUtc")
  private Date lastChangeDateTimeUtc = null;
  @SerializedName("Id")
  private UUID id = null;
  @SerializedName("ValidFromDateTimeUtc")
  private Date validFromDateTimeUtc = null;
  @SerializedName("ValidUntilDateTimeUtc")
  private Date validUntilDateTimeUtc = null;
  @SerializedName("Area")
  private String area = null;
  @SerializedName("Author")
  private String author = null;
  @SerializedName("Title")
  private String title = null;
  @SerializedName("Content")
  private String content = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Date getLastChangeDateTimeUtc() {
    return lastChangeDateTimeUtc;
  }
  public void setLastChangeDateTimeUtc(Date lastChangeDateTimeUtc) {
    this.lastChangeDateTimeUtc = lastChangeDateTimeUtc;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public UUID getId() {
    return id;
  }
  public void setId(UUID id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Date getValidFromDateTimeUtc() {
    return validFromDateTimeUtc;
  }
  public void setValidFromDateTimeUtc(Date validFromDateTimeUtc) {
    this.validFromDateTimeUtc = validFromDateTimeUtc;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Date getValidUntilDateTimeUtc() {
    return validUntilDateTimeUtc;
  }
  public void setValidUntilDateTimeUtc(Date validUntilDateTimeUtc) {
    this.validUntilDateTimeUtc = validUntilDateTimeUtc;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getArea() {
    return area;
  }
  public void setArea(String area) {
    this.area = area;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getAuthor() {
    return author;
  }
  public void setAuthor(String author) {
    this.author = author;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getContent() {
    return content;
  }
  public void setContent(String content) {
    this.content = content;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AnnouncementRecord announcementRecord = (AnnouncementRecord) o;
    return (this.lastChangeDateTimeUtc == null ? announcementRecord.lastChangeDateTimeUtc == null : this.lastChangeDateTimeUtc.equals(announcementRecord.lastChangeDateTimeUtc)) &&
        (this.id == null ? announcementRecord.id == null : this.id.equals(announcementRecord.id)) &&
        (this.validFromDateTimeUtc == null ? announcementRecord.validFromDateTimeUtc == null : this.validFromDateTimeUtc.equals(announcementRecord.validFromDateTimeUtc)) &&
        (this.validUntilDateTimeUtc == null ? announcementRecord.validUntilDateTimeUtc == null : this.validUntilDateTimeUtc.equals(announcementRecord.validUntilDateTimeUtc)) &&
        (this.area == null ? announcementRecord.area == null : this.area.equals(announcementRecord.area)) &&
        (this.author == null ? announcementRecord.author == null : this.author.equals(announcementRecord.author)) &&
        (this.title == null ? announcementRecord.title == null : this.title.equals(announcementRecord.title)) &&
        (this.content == null ? announcementRecord.content == null : this.content.equals(announcementRecord.content));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.lastChangeDateTimeUtc == null ? 0: this.lastChangeDateTimeUtc.hashCode());
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.validFromDateTimeUtc == null ? 0: this.validFromDateTimeUtc.hashCode());
    result = 31 * result + (this.validUntilDateTimeUtc == null ? 0: this.validUntilDateTimeUtc.hashCode());
    result = 31 * result + (this.area == null ? 0: this.area.hashCode());
    result = 31 * result + (this.author == null ? 0: this.author.hashCode());
    result = 31 * result + (this.title == null ? 0: this.title.hashCode());
    result = 31 * result + (this.content == null ? 0: this.content.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnnouncementRecord {\n");
    
    sb.append("  lastChangeDateTimeUtc: ").append(lastChangeDateTimeUtc).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  validFromDateTimeUtc: ").append(validFromDateTimeUtc).append("\n");
    sb.append("  validUntilDateTimeUtc: ").append(validUntilDateTimeUtc).append("\n");
    sb.append("  area: ").append(area).append("\n");
    sb.append("  author: ").append(author).append("\n");
    sb.append("  title: ").append(title).append("\n");
    sb.append("  content: ").append(content).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
