/**
 * Eurofurence API for Mobile Apps
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class AuthenticationResponse {
  
  @SerializedName("Uid")
  private String uid = null;
  @SerializedName("Username")
  private String username = null;
  @SerializedName("Token")
  private String token = null;
  @SerializedName("TokenValidUntil")
  private Date tokenValidUntil = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUid() {
    return uid;
  }
  public void setUid(String uid) {
    this.uid = uid;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUsername() {
    return username;
  }
  public void setUsername(String username) {
    this.username = username;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getToken() {
    return token;
  }
  public void setToken(String token) {
    this.token = token;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getTokenValidUntil() {
    return tokenValidUntil;
  }
  public void setTokenValidUntil(Date tokenValidUntil) {
    this.tokenValidUntil = tokenValidUntil;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthenticationResponse authenticationResponse = (AuthenticationResponse) o;
    return (this.uid == null ? authenticationResponse.uid == null : this.uid.equals(authenticationResponse.uid)) &&
        (this.username == null ? authenticationResponse.username == null : this.username.equals(authenticationResponse.username)) &&
        (this.token == null ? authenticationResponse.token == null : this.token.equals(authenticationResponse.token)) &&
        (this.tokenValidUntil == null ? authenticationResponse.tokenValidUntil == null : this.tokenValidUntil.equals(authenticationResponse.tokenValidUntil));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.uid == null ? 0: this.uid.hashCode());
    result = 31 * result + (this.username == null ? 0: this.username.hashCode());
    result = 31 * result + (this.token == null ? 0: this.token.hashCode());
    result = 31 * result + (this.tokenValidUntil == null ? 0: this.tokenValidUntil.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthenticationResponse {\n");
    
    sb.append("  uid: ").append(uid).append("\n");
    sb.append("  username: ").append(username).append("\n");
    sb.append("  token: ").append(token).append("\n");
    sb.append("  tokenValidUntil: ").append(tokenValidUntil).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
