/**
 * Eurofurence API for Mobile Apps
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.LinkFragment;
import java.util.*;
import java.util.Date;
import java.util.UUID;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class DealerRecord {
  
  @SerializedName("LastChangeDateTimeUtc")
  private Date lastChangeDateTimeUtc = null;
  @SerializedName("Id")
  private UUID id = null;
  @SerializedName("RegistrationNumber")
  private Integer registrationNumber = null;
  @SerializedName("AttendeeNickname")
  private String attendeeNickname = null;
  @SerializedName("DisplayName")
  private String displayName = null;
  @SerializedName("Merchandise")
  private String merchandise = null;
  @SerializedName("ShortDescription")
  private String shortDescription = null;
  @SerializedName("AboutTheArtistText")
  private String aboutTheArtistText = null;
  @SerializedName("AboutTheArtText")
  private String aboutTheArtText = null;
  @SerializedName("Links")
  private List<LinkFragment> links = null;
  @SerializedName("TwitterHandle")
  private String twitterHandle = null;
  @SerializedName("TelegramHandle")
  private String telegramHandle = null;
  @SerializedName("AttendsOnThursday")
  private Boolean attendsOnThursday = null;
  @SerializedName("AttendsOnFriday")
  private Boolean attendsOnFriday = null;
  @SerializedName("AttendsOnSaturday")
  private Boolean attendsOnSaturday = null;
  @SerializedName("ArtPreviewCaption")
  private String artPreviewCaption = null;
  @SerializedName("ArtistThumbnailImageId")
  private UUID artistThumbnailImageId = null;
  @SerializedName("ArtistImageId")
  private UUID artistImageId = null;
  @SerializedName("ArtPreviewImageId")
  private UUID artPreviewImageId = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Date getLastChangeDateTimeUtc() {
    return lastChangeDateTimeUtc;
  }
  public void setLastChangeDateTimeUtc(Date lastChangeDateTimeUtc) {
    this.lastChangeDateTimeUtc = lastChangeDateTimeUtc;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public UUID getId() {
    return id;
  }
  public void setId(UUID id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Integer getRegistrationNumber() {
    return registrationNumber;
  }
  public void setRegistrationNumber(Integer registrationNumber) {
    this.registrationNumber = registrationNumber;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getAttendeeNickname() {
    return attendeeNickname;
  }
  public void setAttendeeNickname(String attendeeNickname) {
    this.attendeeNickname = attendeeNickname;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getDisplayName() {
    return displayName;
  }
  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getMerchandise() {
    return merchandise;
  }
  public void setMerchandise(String merchandise) {
    this.merchandise = merchandise;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getShortDescription() {
    return shortDescription;
  }
  public void setShortDescription(String shortDescription) {
    this.shortDescription = shortDescription;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAboutTheArtistText() {
    return aboutTheArtistText;
  }
  public void setAboutTheArtistText(String aboutTheArtistText) {
    this.aboutTheArtistText = aboutTheArtistText;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAboutTheArtText() {
    return aboutTheArtText;
  }
  public void setAboutTheArtText(String aboutTheArtText) {
    this.aboutTheArtText = aboutTheArtText;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<LinkFragment> getLinks() {
    return links;
  }
  public void setLinks(List<LinkFragment> links) {
    this.links = links;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTwitterHandle() {
    return twitterHandle;
  }
  public void setTwitterHandle(String twitterHandle) {
    this.twitterHandle = twitterHandle;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTelegramHandle() {
    return telegramHandle;
  }
  public void setTelegramHandle(String telegramHandle) {
    this.telegramHandle = telegramHandle;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getAttendsOnThursday() {
    return attendsOnThursday;
  }
  public void setAttendsOnThursday(Boolean attendsOnThursday) {
    this.attendsOnThursday = attendsOnThursday;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getAttendsOnFriday() {
    return attendsOnFriday;
  }
  public void setAttendsOnFriday(Boolean attendsOnFriday) {
    this.attendsOnFriday = attendsOnFriday;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getAttendsOnSaturday() {
    return attendsOnSaturday;
  }
  public void setAttendsOnSaturday(Boolean attendsOnSaturday) {
    this.attendsOnSaturday = attendsOnSaturday;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getArtPreviewCaption() {
    return artPreviewCaption;
  }
  public void setArtPreviewCaption(String artPreviewCaption) {
    this.artPreviewCaption = artPreviewCaption;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public UUID getArtistThumbnailImageId() {
    return artistThumbnailImageId;
  }
  public void setArtistThumbnailImageId(UUID artistThumbnailImageId) {
    this.artistThumbnailImageId = artistThumbnailImageId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public UUID getArtistImageId() {
    return artistImageId;
  }
  public void setArtistImageId(UUID artistImageId) {
    this.artistImageId = artistImageId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public UUID getArtPreviewImageId() {
    return artPreviewImageId;
  }
  public void setArtPreviewImageId(UUID artPreviewImageId) {
    this.artPreviewImageId = artPreviewImageId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DealerRecord dealerRecord = (DealerRecord) o;
    return (this.lastChangeDateTimeUtc == null ? dealerRecord.lastChangeDateTimeUtc == null : this.lastChangeDateTimeUtc.equals(dealerRecord.lastChangeDateTimeUtc)) &&
        (this.id == null ? dealerRecord.id == null : this.id.equals(dealerRecord.id)) &&
        (this.registrationNumber == null ? dealerRecord.registrationNumber == null : this.registrationNumber.equals(dealerRecord.registrationNumber)) &&
        (this.attendeeNickname == null ? dealerRecord.attendeeNickname == null : this.attendeeNickname.equals(dealerRecord.attendeeNickname)) &&
        (this.displayName == null ? dealerRecord.displayName == null : this.displayName.equals(dealerRecord.displayName)) &&
        (this.merchandise == null ? dealerRecord.merchandise == null : this.merchandise.equals(dealerRecord.merchandise)) &&
        (this.shortDescription == null ? dealerRecord.shortDescription == null : this.shortDescription.equals(dealerRecord.shortDescription)) &&
        (this.aboutTheArtistText == null ? dealerRecord.aboutTheArtistText == null : this.aboutTheArtistText.equals(dealerRecord.aboutTheArtistText)) &&
        (this.aboutTheArtText == null ? dealerRecord.aboutTheArtText == null : this.aboutTheArtText.equals(dealerRecord.aboutTheArtText)) &&
        (this.links == null ? dealerRecord.links == null : this.links.equals(dealerRecord.links)) &&
        (this.twitterHandle == null ? dealerRecord.twitterHandle == null : this.twitterHandle.equals(dealerRecord.twitterHandle)) &&
        (this.telegramHandle == null ? dealerRecord.telegramHandle == null : this.telegramHandle.equals(dealerRecord.telegramHandle)) &&
        (this.attendsOnThursday == null ? dealerRecord.attendsOnThursday == null : this.attendsOnThursday.equals(dealerRecord.attendsOnThursday)) &&
        (this.attendsOnFriday == null ? dealerRecord.attendsOnFriday == null : this.attendsOnFriday.equals(dealerRecord.attendsOnFriday)) &&
        (this.attendsOnSaturday == null ? dealerRecord.attendsOnSaturday == null : this.attendsOnSaturday.equals(dealerRecord.attendsOnSaturday)) &&
        (this.artPreviewCaption == null ? dealerRecord.artPreviewCaption == null : this.artPreviewCaption.equals(dealerRecord.artPreviewCaption)) &&
        (this.artistThumbnailImageId == null ? dealerRecord.artistThumbnailImageId == null : this.artistThumbnailImageId.equals(dealerRecord.artistThumbnailImageId)) &&
        (this.artistImageId == null ? dealerRecord.artistImageId == null : this.artistImageId.equals(dealerRecord.artistImageId)) &&
        (this.artPreviewImageId == null ? dealerRecord.artPreviewImageId == null : this.artPreviewImageId.equals(dealerRecord.artPreviewImageId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.lastChangeDateTimeUtc == null ? 0: this.lastChangeDateTimeUtc.hashCode());
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.registrationNumber == null ? 0: this.registrationNumber.hashCode());
    result = 31 * result + (this.attendeeNickname == null ? 0: this.attendeeNickname.hashCode());
    result = 31 * result + (this.displayName == null ? 0: this.displayName.hashCode());
    result = 31 * result + (this.merchandise == null ? 0: this.merchandise.hashCode());
    result = 31 * result + (this.shortDescription == null ? 0: this.shortDescription.hashCode());
    result = 31 * result + (this.aboutTheArtistText == null ? 0: this.aboutTheArtistText.hashCode());
    result = 31 * result + (this.aboutTheArtText == null ? 0: this.aboutTheArtText.hashCode());
    result = 31 * result + (this.links == null ? 0: this.links.hashCode());
    result = 31 * result + (this.twitterHandle == null ? 0: this.twitterHandle.hashCode());
    result = 31 * result + (this.telegramHandle == null ? 0: this.telegramHandle.hashCode());
    result = 31 * result + (this.attendsOnThursday == null ? 0: this.attendsOnThursday.hashCode());
    result = 31 * result + (this.attendsOnFriday == null ? 0: this.attendsOnFriday.hashCode());
    result = 31 * result + (this.attendsOnSaturday == null ? 0: this.attendsOnSaturday.hashCode());
    result = 31 * result + (this.artPreviewCaption == null ? 0: this.artPreviewCaption.hashCode());
    result = 31 * result + (this.artistThumbnailImageId == null ? 0: this.artistThumbnailImageId.hashCode());
    result = 31 * result + (this.artistImageId == null ? 0: this.artistImageId.hashCode());
    result = 31 * result + (this.artPreviewImageId == null ? 0: this.artPreviewImageId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DealerRecord {\n");
    
    sb.append("  lastChangeDateTimeUtc: ").append(lastChangeDateTimeUtc).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  registrationNumber: ").append(registrationNumber).append("\n");
    sb.append("  attendeeNickname: ").append(attendeeNickname).append("\n");
    sb.append("  displayName: ").append(displayName).append("\n");
    sb.append("  merchandise: ").append(merchandise).append("\n");
    sb.append("  shortDescription: ").append(shortDescription).append("\n");
    sb.append("  aboutTheArtistText: ").append(aboutTheArtistText).append("\n");
    sb.append("  aboutTheArtText: ").append(aboutTheArtText).append("\n");
    sb.append("  links: ").append(links).append("\n");
    sb.append("  twitterHandle: ").append(twitterHandle).append("\n");
    sb.append("  telegramHandle: ").append(telegramHandle).append("\n");
    sb.append("  attendsOnThursday: ").append(attendsOnThursday).append("\n");
    sb.append("  attendsOnFriday: ").append(attendsOnFriday).append("\n");
    sb.append("  attendsOnSaturday: ").append(attendsOnSaturday).append("\n");
    sb.append("  artPreviewCaption: ").append(artPreviewCaption).append("\n");
    sb.append("  artistThumbnailImageId: ").append(artistThumbnailImageId).append("\n");
    sb.append("  artistImageId: ").append(artistImageId).append("\n");
    sb.append("  artPreviewImageId: ").append(artPreviewImageId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
