/**
 * Eurofurence API for Mobile Apps
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.EventConferenceDayRecord;
import java.util.*;
import java.util.Date;
import java.util.UUID;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class DeltaResponseEventConferenceDayRecord {
  
  @SerializedName("StorageLastChangeDateTimeUtc")
  private Date storageLastChangeDateTimeUtc = null;
  @SerializedName("StorageDeltaStartChangeDateTimeUtc")
  private Date storageDeltaStartChangeDateTimeUtc = null;
  @SerializedName("RemoveAllBeforeInsert")
  private Boolean removeAllBeforeInsert = null;
  @SerializedName("ChangedEntities")
  private List<EventConferenceDayRecord> changedEntities = null;
  @SerializedName("DeletedEntities")
  private List<UUID> deletedEntities = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getStorageLastChangeDateTimeUtc() {
    return storageLastChangeDateTimeUtc;
  }
  public void setStorageLastChangeDateTimeUtc(Date storageLastChangeDateTimeUtc) {
    this.storageLastChangeDateTimeUtc = storageLastChangeDateTimeUtc;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getStorageDeltaStartChangeDateTimeUtc() {
    return storageDeltaStartChangeDateTimeUtc;
  }
  public void setStorageDeltaStartChangeDateTimeUtc(Date storageDeltaStartChangeDateTimeUtc) {
    this.storageDeltaStartChangeDateTimeUtc = storageDeltaStartChangeDateTimeUtc;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getRemoveAllBeforeInsert() {
    return removeAllBeforeInsert;
  }
  public void setRemoveAllBeforeInsert(Boolean removeAllBeforeInsert) {
    this.removeAllBeforeInsert = removeAllBeforeInsert;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<EventConferenceDayRecord> getChangedEntities() {
    return changedEntities;
  }
  public void setChangedEntities(List<EventConferenceDayRecord> changedEntities) {
    this.changedEntities = changedEntities;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<UUID> getDeletedEntities() {
    return deletedEntities;
  }
  public void setDeletedEntities(List<UUID> deletedEntities) {
    this.deletedEntities = deletedEntities;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeltaResponseEventConferenceDayRecord deltaResponseEventConferenceDayRecord = (DeltaResponseEventConferenceDayRecord) o;
    return (this.storageLastChangeDateTimeUtc == null ? deltaResponseEventConferenceDayRecord.storageLastChangeDateTimeUtc == null : this.storageLastChangeDateTimeUtc.equals(deltaResponseEventConferenceDayRecord.storageLastChangeDateTimeUtc)) &&
        (this.storageDeltaStartChangeDateTimeUtc == null ? deltaResponseEventConferenceDayRecord.storageDeltaStartChangeDateTimeUtc == null : this.storageDeltaStartChangeDateTimeUtc.equals(deltaResponseEventConferenceDayRecord.storageDeltaStartChangeDateTimeUtc)) &&
        (this.removeAllBeforeInsert == null ? deltaResponseEventConferenceDayRecord.removeAllBeforeInsert == null : this.removeAllBeforeInsert.equals(deltaResponseEventConferenceDayRecord.removeAllBeforeInsert)) &&
        (this.changedEntities == null ? deltaResponseEventConferenceDayRecord.changedEntities == null : this.changedEntities.equals(deltaResponseEventConferenceDayRecord.changedEntities)) &&
        (this.deletedEntities == null ? deltaResponseEventConferenceDayRecord.deletedEntities == null : this.deletedEntities.equals(deltaResponseEventConferenceDayRecord.deletedEntities));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.storageLastChangeDateTimeUtc == null ? 0: this.storageLastChangeDateTimeUtc.hashCode());
    result = 31 * result + (this.storageDeltaStartChangeDateTimeUtc == null ? 0: this.storageDeltaStartChangeDateTimeUtc.hashCode());
    result = 31 * result + (this.removeAllBeforeInsert == null ? 0: this.removeAllBeforeInsert.hashCode());
    result = 31 * result + (this.changedEntities == null ? 0: this.changedEntities.hashCode());
    result = 31 * result + (this.deletedEntities == null ? 0: this.deletedEntities.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeltaResponseEventConferenceDayRecord {\n");
    
    sb.append("  storageLastChangeDateTimeUtc: ").append(storageLastChangeDateTimeUtc).append("\n");
    sb.append("  storageDeltaStartChangeDateTimeUtc: ").append(storageDeltaStartChangeDateTimeUtc).append("\n");
    sb.append("  removeAllBeforeInsert: ").append(removeAllBeforeInsert).append("\n");
    sb.append("  changedEntities: ").append(changedEntities).append("\n");
    sb.append("  deletedEntities: ").append(deletedEntities).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
