/**
 * Eurofurence API for Mobile Apps
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Date;
import java.util.UUID;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class KnowledgeGroupRecord {
  
  @SerializedName("LastChangeDateTimeUtc")
  private Date lastChangeDateTimeUtc = null;
  @SerializedName("Id")
  private UUID id = null;
  @SerializedName("Name")
  private String name = null;
  @SerializedName("Description")
  private String description = null;
  @SerializedName("Order")
  private Integer order = null;
  @SerializedName("ShowInHamburgerMenu")
  private Boolean showInHamburgerMenu = null;
  @SerializedName("FontAwesomeIconCharacterUnicodeAddress")
  private String fontAwesomeIconCharacterUnicodeAddress = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Date getLastChangeDateTimeUtc() {
    return lastChangeDateTimeUtc;
  }
  public void setLastChangeDateTimeUtc(Date lastChangeDateTimeUtc) {
    this.lastChangeDateTimeUtc = lastChangeDateTimeUtc;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public UUID getId() {
    return id;
  }
  public void setId(UUID id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Integer getOrder() {
    return order;
  }
  public void setOrder(Integer order) {
    this.order = order;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getShowInHamburgerMenu() {
    return showInHamburgerMenu;
  }
  public void setShowInHamburgerMenu(Boolean showInHamburgerMenu) {
    this.showInHamburgerMenu = showInHamburgerMenu;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFontAwesomeIconCharacterUnicodeAddress() {
    return fontAwesomeIconCharacterUnicodeAddress;
  }
  public void setFontAwesomeIconCharacterUnicodeAddress(String fontAwesomeIconCharacterUnicodeAddress) {
    this.fontAwesomeIconCharacterUnicodeAddress = fontAwesomeIconCharacterUnicodeAddress;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KnowledgeGroupRecord knowledgeGroupRecord = (KnowledgeGroupRecord) o;
    return (this.lastChangeDateTimeUtc == null ? knowledgeGroupRecord.lastChangeDateTimeUtc == null : this.lastChangeDateTimeUtc.equals(knowledgeGroupRecord.lastChangeDateTimeUtc)) &&
        (this.id == null ? knowledgeGroupRecord.id == null : this.id.equals(knowledgeGroupRecord.id)) &&
        (this.name == null ? knowledgeGroupRecord.name == null : this.name.equals(knowledgeGroupRecord.name)) &&
        (this.description == null ? knowledgeGroupRecord.description == null : this.description.equals(knowledgeGroupRecord.description)) &&
        (this.order == null ? knowledgeGroupRecord.order == null : this.order.equals(knowledgeGroupRecord.order)) &&
        (this.showInHamburgerMenu == null ? knowledgeGroupRecord.showInHamburgerMenu == null : this.showInHamburgerMenu.equals(knowledgeGroupRecord.showInHamburgerMenu)) &&
        (this.fontAwesomeIconCharacterUnicodeAddress == null ? knowledgeGroupRecord.fontAwesomeIconCharacterUnicodeAddress == null : this.fontAwesomeIconCharacterUnicodeAddress.equals(knowledgeGroupRecord.fontAwesomeIconCharacterUnicodeAddress));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.lastChangeDateTimeUtc == null ? 0: this.lastChangeDateTimeUtc.hashCode());
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.description == null ? 0: this.description.hashCode());
    result = 31 * result + (this.order == null ? 0: this.order.hashCode());
    result = 31 * result + (this.showInHamburgerMenu == null ? 0: this.showInHamburgerMenu.hashCode());
    result = 31 * result + (this.fontAwesomeIconCharacterUnicodeAddress == null ? 0: this.fontAwesomeIconCharacterUnicodeAddress.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class KnowledgeGroupRecord {\n");
    
    sb.append("  lastChangeDateTimeUtc: ").append(lastChangeDateTimeUtc).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("  order: ").append(order).append("\n");
    sb.append("  showInHamburgerMenu: ").append(showInHamburgerMenu).append("\n");
    sb.append("  fontAwesomeIconCharacterUnicodeAddress: ").append(fontAwesomeIconCharacterUnicodeAddress).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
