/**
 * Eurofurence API for Mobile Apps
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.LinkFragment;
import java.util.*;
import java.util.Date;
import java.util.UUID;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class KnowledgeEntryRecord {
  
  @SerializedName("LastChangeDateTimeUtc")
  private Date lastChangeDateTimeUtc = null;
  @SerializedName("Id")
  private UUID id = null;
  @SerializedName("KnowledgeGroupId")
  private UUID knowledgeGroupId = null;
  @SerializedName("Title")
  private String title = null;
  @SerializedName("Text")
  private String text = null;
  @SerializedName("Order")
  private Integer order = null;
  @SerializedName("Links")
  private List<LinkFragment> links = null;
  @SerializedName("ImageIds")
  private List<UUID> imageIds = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Date getLastChangeDateTimeUtc() {
    return lastChangeDateTimeUtc;
  }
  public void setLastChangeDateTimeUtc(Date lastChangeDateTimeUtc) {
    this.lastChangeDateTimeUtc = lastChangeDateTimeUtc;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public UUID getId() {
    return id;
  }
  public void setId(UUID id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public UUID getKnowledgeGroupId() {
    return knowledgeGroupId;
  }
  public void setKnowledgeGroupId(UUID knowledgeGroupId) {
    this.knowledgeGroupId = knowledgeGroupId;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getText() {
    return text;
  }
  public void setText(String text) {
    this.text = text;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Integer getOrder() {
    return order;
  }
  public void setOrder(Integer order) {
    this.order = order;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<LinkFragment> getLinks() {
    return links;
  }
  public void setLinks(List<LinkFragment> links) {
    this.links = links;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<UUID> getImageIds() {
    return imageIds;
  }
  public void setImageIds(List<UUID> imageIds) {
    this.imageIds = imageIds;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KnowledgeEntryRecord knowledgeEntryRecord = (KnowledgeEntryRecord) o;
    return (this.lastChangeDateTimeUtc == null ? knowledgeEntryRecord.lastChangeDateTimeUtc == null : this.lastChangeDateTimeUtc.equals(knowledgeEntryRecord.lastChangeDateTimeUtc)) &&
        (this.id == null ? knowledgeEntryRecord.id == null : this.id.equals(knowledgeEntryRecord.id)) &&
        (this.knowledgeGroupId == null ? knowledgeEntryRecord.knowledgeGroupId == null : this.knowledgeGroupId.equals(knowledgeEntryRecord.knowledgeGroupId)) &&
        (this.title == null ? knowledgeEntryRecord.title == null : this.title.equals(knowledgeEntryRecord.title)) &&
        (this.text == null ? knowledgeEntryRecord.text == null : this.text.equals(knowledgeEntryRecord.text)) &&
        (this.order == null ? knowledgeEntryRecord.order == null : this.order.equals(knowledgeEntryRecord.order)) &&
        (this.links == null ? knowledgeEntryRecord.links == null : this.links.equals(knowledgeEntryRecord.links)) &&
        (this.imageIds == null ? knowledgeEntryRecord.imageIds == null : this.imageIds.equals(knowledgeEntryRecord.imageIds));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.lastChangeDateTimeUtc == null ? 0: this.lastChangeDateTimeUtc.hashCode());
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.knowledgeGroupId == null ? 0: this.knowledgeGroupId.hashCode());
    result = 31 * result + (this.title == null ? 0: this.title.hashCode());
    result = 31 * result + (this.text == null ? 0: this.text.hashCode());
    result = 31 * result + (this.order == null ? 0: this.order.hashCode());
    result = 31 * result + (this.links == null ? 0: this.links.hashCode());
    result = 31 * result + (this.imageIds == null ? 0: this.imageIds.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class KnowledgeEntryRecord {\n");
    
    sb.append("  lastChangeDateTimeUtc: ").append(lastChangeDateTimeUtc).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  knowledgeGroupId: ").append(knowledgeGroupId).append("\n");
    sb.append("  title: ").append(title).append("\n");
    sb.append("  text: ").append(text).append("\n");
    sb.append("  order: ").append(order).append("\n");
    sb.append("  links: ").append(links).append("\n");
    sb.append("  imageIds: ").append(imageIds).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
