/**
 * Eurofurence API for Mobile Apps
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class LinkFragment {
  
  public enum FragmentTypeEnum {
     WebExternal,  MapExternal,  MapInternal,  DealerDetail, 
  };
  @SerializedName("FragmentType")
  private FragmentTypeEnum fragmentType = null;
  @SerializedName("Name")
  private String name = null;
  @SerializedName("Target")
  private String target = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public FragmentTypeEnum getFragmentType() {
    return fragmentType;
  }
  public void setFragmentType(FragmentTypeEnum fragmentType) {
    this.fragmentType = fragmentType;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   * * For FragmentType `DealerDetail`: The `Id` of the dealer record the link is referencing to.  * For FragmentType `MapExternal`: An stringified json object.    * Acceptable properties and their expected value (type):      * `name` - name of target POI (*string*)      * `street` - street name (*string*)      * `house` - house humber (*string*)      * `zip` - zip code of city (*string*)      * `city` - city (*string*)      * `country` - country (*string*)      * `country-a3` - ISO 3166-1 alpha-3 code for country [http://unstats.un.org/unsd/methods/m49/m49alpha.htm] (*string*)      * `lat` - latitude (*decimal*)      * `lon` - longitude (*decimal*)    * Example:      * `{ name: \"Estrel Hotel Berlin\", house: \"225\", street: \"Sonnenallee\", zip: \"12057\", city: \"Berlin\", country: \"Germany\", lat: 52.473336, lon: 13.458729 }`
   **/
  @ApiModelProperty(required = true, value = "* For FragmentType `DealerDetail`: The `Id` of the dealer record the link is referencing to.  * For FragmentType `MapExternal`: An stringified json object.    * Acceptable properties and their expected value (type):      * `name` - name of target POI (*string*)      * `street` - street name (*string*)      * `house` - house humber (*string*)      * `zip` - zip code of city (*string*)      * `city` - city (*string*)      * `country` - country (*string*)      * `country-a3` - ISO 3166-1 alpha-3 code for country [http://unstats.un.org/unsd/methods/m49/m49alpha.htm] (*string*)      * `lat` - latitude (*decimal*)      * `lon` - longitude (*decimal*)    * Example:      * `{ name: \"Estrel Hotel Berlin\", house: \"225\", street: \"Sonnenallee\", zip: \"12057\", city: \"Berlin\", country: \"Germany\", lat: 52.473336, lon: 13.458729 }`")
  public String getTarget() {
    return target;
  }
  public void setTarget(String target) {
    this.target = target;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LinkFragment linkFragment = (LinkFragment) o;
    return (this.fragmentType == null ? linkFragment.fragmentType == null : this.fragmentType.equals(linkFragment.fragmentType)) &&
        (this.name == null ? linkFragment.name == null : this.name.equals(linkFragment.name)) &&
        (this.target == null ? linkFragment.target == null : this.target.equals(linkFragment.target));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.fragmentType == null ? 0: this.fragmentType.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.target == null ? 0: this.target.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class LinkFragment {\n");
    
    sb.append("  fragmentType: ").append(fragmentType).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  target: ").append(target).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
