/**
 * Eurofurence API for Mobile Apps
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.LinkFragment;
import java.util.UUID;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class MapEntryRecord {
  
  @SerializedName("Id")
  private UUID id = null;
  @SerializedName("RelativeX")
  private Double relativeX = null;
  @SerializedName("RelativeY")
  private Double relativeY = null;
  @SerializedName("RelativeTapRadius")
  private Double relativeTapRadius = null;
  @SerializedName("Link")
  private LinkFragment link = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public UUID getId() {
    return id;
  }
  public void setId(UUID id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getRelativeX() {
    return relativeX;
  }
  public void setRelativeX(Double relativeX) {
    this.relativeX = relativeX;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getRelativeY() {
    return relativeY;
  }
  public void setRelativeY(Double relativeY) {
    this.relativeY = relativeY;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getRelativeTapRadius() {
    return relativeTapRadius;
  }
  public void setRelativeTapRadius(Double relativeTapRadius) {
    this.relativeTapRadius = relativeTapRadius;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public LinkFragment getLink() {
    return link;
  }
  public void setLink(LinkFragment link) {
    this.link = link;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MapEntryRecord mapEntryRecord = (MapEntryRecord) o;
    return (this.id == null ? mapEntryRecord.id == null : this.id.equals(mapEntryRecord.id)) &&
        (this.relativeX == null ? mapEntryRecord.relativeX == null : this.relativeX.equals(mapEntryRecord.relativeX)) &&
        (this.relativeY == null ? mapEntryRecord.relativeY == null : this.relativeY.equals(mapEntryRecord.relativeY)) &&
        (this.relativeTapRadius == null ? mapEntryRecord.relativeTapRadius == null : this.relativeTapRadius.equals(mapEntryRecord.relativeTapRadius)) &&
        (this.link == null ? mapEntryRecord.link == null : this.link.equals(mapEntryRecord.link));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.relativeX == null ? 0: this.relativeX.hashCode());
    result = 31 * result + (this.relativeY == null ? 0: this.relativeY.hashCode());
    result = 31 * result + (this.relativeTapRadius == null ? 0: this.relativeTapRadius.hashCode());
    result = 31 * result + (this.link == null ? 0: this.link.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class MapEntryRecord {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  relativeX: ").append(relativeX).append("\n");
    sb.append("  relativeY: ").append(relativeY).append("\n");
    sb.append("  relativeTapRadius: ").append(relativeTapRadius).append("\n");
    sb.append("  link: ").append(link).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
