/**
 * Eurofurence API for Mobile Apps
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class SendPrivateMessageRequest {
  
  @SerializedName("RecipientUid")
  private String recipientUid = null;
  @SerializedName("AuthorName")
  private String authorName = null;
  @SerializedName("ToastTitle")
  private String toastTitle = null;
  @SerializedName("ToastMessage")
  private String toastMessage = null;
  @SerializedName("Subject")
  private String subject = null;
  @SerializedName("Message")
  private String message = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRecipientUid() {
    return recipientUid;
  }
  public void setRecipientUid(String recipientUid) {
    this.recipientUid = recipientUid;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAuthorName() {
    return authorName;
  }
  public void setAuthorName(String authorName) {
    this.authorName = authorName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getToastTitle() {
    return toastTitle;
  }
  public void setToastTitle(String toastTitle) {
    this.toastTitle = toastTitle;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getToastMessage() {
    return toastMessage;
  }
  public void setToastMessage(String toastMessage) {
    this.toastMessage = toastMessage;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSubject() {
    return subject;
  }
  public void setSubject(String subject) {
    this.subject = subject;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMessage() {
    return message;
  }
  public void setMessage(String message) {
    this.message = message;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SendPrivateMessageRequest sendPrivateMessageRequest = (SendPrivateMessageRequest) o;
    return (this.recipientUid == null ? sendPrivateMessageRequest.recipientUid == null : this.recipientUid.equals(sendPrivateMessageRequest.recipientUid)) &&
        (this.authorName == null ? sendPrivateMessageRequest.authorName == null : this.authorName.equals(sendPrivateMessageRequest.authorName)) &&
        (this.toastTitle == null ? sendPrivateMessageRequest.toastTitle == null : this.toastTitle.equals(sendPrivateMessageRequest.toastTitle)) &&
        (this.toastMessage == null ? sendPrivateMessageRequest.toastMessage == null : this.toastMessage.equals(sendPrivateMessageRequest.toastMessage)) &&
        (this.subject == null ? sendPrivateMessageRequest.subject == null : this.subject.equals(sendPrivateMessageRequest.subject)) &&
        (this.message == null ? sendPrivateMessageRequest.message == null : this.message.equals(sendPrivateMessageRequest.message));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.recipientUid == null ? 0: this.recipientUid.hashCode());
    result = 31 * result + (this.authorName == null ? 0: this.authorName.hashCode());
    result = 31 * result + (this.toastTitle == null ? 0: this.toastTitle.hashCode());
    result = 31 * result + (this.toastMessage == null ? 0: this.toastMessage.hashCode());
    result = 31 * result + (this.subject == null ? 0: this.subject.hashCode());
    result = 31 * result + (this.message == null ? 0: this.message.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SendPrivateMessageRequest {\n");
    
    sb.append("  recipientUid: ").append(recipientUid).append("\n");
    sb.append("  authorName: ").append(authorName).append("\n");
    sb.append("  toastTitle: ").append(toastTitle).append("\n");
    sb.append("  toastMessage: ").append(toastMessage).append("\n");
    sb.append("  subject: ").append(subject).append("\n");
    sb.append("  message: ").append(message).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
